/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Page = {
    _id: string;
    _type: "page";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    overview?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
    }>;
    body?: Array<
        | {
              children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
              }>;
              style?: "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
          }
        | ({
              _key: string;
          } & Timeline)
        | {
              asset?: {
                  _ref: string;
                  _type: "reference";
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
              };
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              caption?: string;
              alt?: string;
              _type: "image";
              _key: string;
          }
    >;
};

export type ColorTheme = {
    _id: string;
    _type: "colorTheme";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    text?: Color;
    background?: Color;
};

export type Milestone = {
    _type: "milestone";
    title?: string;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    tags?: Array<string>;
    duration?: Duration;
};

export type Duration = {
    _type: "duration";
    start?: string;
    end?: string;
};

export type Timeline = {
    _type: "timeline";
    items?: Array<{
        title?: string;
        milestones?: Array<
            {
                _key: string;
            } & Milestone
        >;
        _type: "item";
        _key: string;
    }>;
};

export type MenuLinks = Array<
    | ({
          _key: string;
      } & LinkInternal)
    | ({
          _key: string;
      } & LinkExternal)
>;

export type Instagram = {
    _type: "instagram";
    url?: string;
};

export type ImageFeature = {
    _type: "imageFeature";
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    variant?: string | "caption" | "callToAction";
    caption?: string;
    callToAction?: ImageCallToAction;
};

export type Images = {
    _type: "images";
    imageFeatures?: Array<
        {
            _key: string;
        } & ImageFeature
    >;
    fullWidth?: boolean;
    verticalAlign?: "top" | "center" | "bottom";
};

export type ImageCallToAction = {
    _type: "imageCallToAction";
    title?: string;
    link?: Array<
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
};

export type Grid = {
    _type: "grid";
    items?: Array<
        {
            _key: string;
        } & GridItem
    >;
};

export type GridItem = {
    _type: "gridItem";
    title?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    body?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
            | ({
                  _key: string;
              } & LinkEmail)
            | ({
                  _key: string;
              } & LinkInternal)
            | ({
                  _key: string;
              } & LinkExternal)
        >;
        level?: number;
        _type: "block";
        _key: string;
    }>;
};

export type CallToAction = {
    _type: "callToAction";
    layout?: "left" | "right";
    title?: string;
    portableText?: string;
    link?: Array<
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
    content?: Array<{
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
    }>;
};

export type Callout = {
    _type: "callout";
    text?: string;
    link?: Array<
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
};

export type Accordion = {
    _type: "accordion";
    groups?: Array<
        {
            _key: string;
        } & AccordionGroup
    >;
};

export type AccordionGroup = {
    _type: "accordionGroup";
    title?: string;
    body?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
        }>;
        style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
            | ({
                  _key: string;
              } & LinkEmail)
            | ({
                  _key: string;
              } & LinkInternal)
            | ({
                  _key: string;
              } & LinkExternal)
        >;
        level?: number;
        _type: "block";
        _key: string;
    }>;
};

export type PortableTextSimple = Array<{
    children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<
        | ({
              _key: string;
          } & LinkEmail)
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
    level?: number;
    _type: "block";
    _key: string;
}>;

export type PortableText = Array<
    | {
          children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
          }>;
          style?:
              | "normal"
              | "h1"
              | "h2"
              | "h3"
              | "h4"
              | "h5"
              | "h6"
              | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<
              | ({
                    _key: string;
                } & LinkEmail)
              | ({
                    _key: string;
                } & LinkInternal)
              | ({
                    _key: string;
                } & LinkExternal)
          >;
          level?: number;
          _type: "block";
          _key: string;
      }
    | ({
          _key: string;
      } & Accordion)
    | ({
          _key: string;
      } & Callout)
    | ({
          _key: string;
      } & Grid)
    | ({
          _key: string;
      } & Images)
    | ({
          _key: string;
      } & Instagram)
>;

export type PortableColorTitle = Array<{
    children?: Array<{
        marks?: Array<"purple" | string>;
        text?: string;
        _type: "span";
        _key: string;
    }>;
    style?: "normal";
    markDefs?: Array<{
        _key: string;
    }>;
    _type: "block";
    _key: string;
}>;

export type LinkInternal = {
    _type: "linkInternal";
    reference?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "home";
    };
};

export type LinkExternal = {
    _type: "linkExternal";
    url?: string;
    newWindow?: boolean;
};

export type LinkEmail = {
    _type: "linkEmail";
    email?: string;
};

export type InternationalizedArrayStringValue = {
    _type: "internationalizedArrayStringValue";
    value?: string;
};

export type InternationalizedArrayString = Array<
    {
        _key: string;
    } & InternationalizedArrayStringValue
>;

export type TranslationMetadata = {
    _id: string;
    _type: "translation.metadata";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    translations?: Array<
        {
            _key: string;
        } & InternationalizedArrayReferenceValue
    >;
    schemaTypes?: Array<string>;
};

export type InternationalizedArrayReferenceValue = {
    _type: "internationalizedArrayReferenceValue";
    value?:
        | {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "home";
          }
        | {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "settings";
          };
};

export type Settings = {
    _id: string;
    _type: "settings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    language?: string;
    menu?: Menu;
    footer?: FooterSettings;
    notFoundPage?: NotFoundPage;
    seo?: Seo;
};

export type NotFoundPage = {
    _type: "notFoundPage";
    title?: string;
    body?: string;
};

export type FooterSettings = {
    _type: "footerSettings";
    links?: Array<
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
    text?: PortableTextSimple;
};

export type Menu = {
    _type: "menu";
    links?: MenuLinks;
};

export type Home = {
    _id: string;
    _type: "home";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    language?: string;
    hero?: Hero;
    seo?: Seo;
    ctaSectionJoinUs?: CallToAction;
    ctaSectionOrder?: CallToAction;
    ctaSectionWriteUs?: CallToAction;
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type Seo = {
    _type: "seo";
    title?: string;
    description?: string;
    image?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
};

export type Hero = {
    _type: "hero";
    title?: string;
    description?: string;
    link?: Array<
        | ({
              _key: string;
          } & LinkInternal)
        | ({
              _key: string;
          } & LinkExternal)
    >;
};

export type InternationalizedArrayReference = Array<
    {
        _key: string;
    } & InternationalizedArrayReferenceValue
>;

export type Color = {
    _type: "color";
    hex?: string;
    alpha?: number;
    hsl?: HslaColor;
    hsv?: HsvaColor;
    rgb?: RgbaColor;
};

export type RgbaColor = {
    _type: "rgbaColor";
    r?: number;
    g?: number;
    b?: number;
    a?: number;
};

export type HsvaColor = {
    _type: "hsvaColor";
    h?: number;
    s?: number;
    v?: number;
    a?: number;
};

export type HslaColor = {
    _type: "hslaColor";
    h?: number;
    s?: number;
    l?: number;
    a?: number;
};

export type MediaTag = {
    _id: string;
    _type: "media.tag";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: Slug;
};

export type Slug = {
    _type: "slug";
    current?: string;
    source?: string;
};

export type AllSanitySchemaTypes =
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityFileAsset
    | Geopoint
    | Page
    | ColorTheme
    | Milestone
    | Duration
    | Timeline
    | MenuLinks
    | Instagram
    | ImageFeature
    | Images
    | ImageCallToAction
    | Grid
    | GridItem
    | CallToAction
    | Callout
    | Accordion
    | AccordionGroup
    | PortableTextSimple
    | PortableText
    | PortableColorTitle
    | LinkInternal
    | LinkExternal
    | LinkEmail
    | InternationalizedArrayStringValue
    | InternationalizedArrayString
    | TranslationMetadata
    | InternationalizedArrayReferenceValue
    | Settings
    | NotFoundPage
    | FooterSettings
    | Menu
    | Home
    | SanityImageCrop
    | SanityImageHotspot
    | SanityImageAsset
    | SanityAssetSourceData
    | SanityImageMetadata
    | Seo
    | Hero
    | InternationalizedArrayReference
    | Color
    | RgbaColor
    | HsvaColor
    | HslaColor
    | MediaTag
    | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: homePageQuery
// Query:   *[_type == "home"][0]{    _id,    title,    hero,    language  }
export type HomePageQueryResult = {
    _id: string;
    title: null;
    hero: Hero | null;
    language: string | null;
} | null;
// Variable: settingsQuery
// Query:   *[_type == "settings"][0]{    footer,    menuItems[]->{      _type,      "slug": slug.current,      title    },    ogImage,  }
export type SettingsQueryResult = {
    footer: FooterSettings | null;
    menuItems: null;
    ogImage: null;
} | null;
