export const domainList = [
    "AI/ML",
    "AR/VR",
    "Advertising",
    "Agency",
    "Agriculture",
    "Architecture",
    "Art and illustration",
    "Automotive",
    "Aviation",
    "Big Data",
    "Blockchain",
    "Beauty and health",
    "BI/Data Warehouse",
    "Cinema and TV",
    "Cloud Computing",
    "Corporate Systems",
    "Corporate websites",
    "Data Science",
    "Dating",
    "Design",
    "Domains/Hosting",
    "Ecommerce",
    "Education",
    "Embedded",
    "Energy",
    "Enterprise",
    "Events",
    "Fashion",
    "Finance",
    "Food and drinks",
    "Games and entertainment",
    "Gambling",
    "Gamedev",
    "Geospatial",
    "Hardware",
    "Healthcare",
    "High Load Systems",
    "Hospitality",
    "Insurance",
    "IoT",
    "Landing pages",
    "Legal",
    "Logistics",
    "Non-profit and charity organizations",
    "Magazine/Newspaper/Blog",
    "Manufacturing",
    "Marketing",
    "Medicine",
    "Media",
    "Music",
    "Miltech",
    "Mobile",
    "Personal websites",
    "Photo and video",
    "Portfolio",
    "Product pages",
    "Public relations",
    "Real estate",
    "Retail",
    "Restaurant and hotel business",
    "Robotics",
    "SaaS",
    "Security",
    "SMM",
    "Sports",
    "Startup",
    "Telecom",
    "Traveling",
    "Uberfication",
    "Web",
    "Wellbeing",
    "Wellness",
    "Other",
] as const;

export type DomainType = (typeof domainList)[number];
